Setup
cyder/SyncPod-BFF pull request #1
Opened 2019-01-29 17:29 UTC by euglena1215

tslint/tslintはまた今度

2019-01-30 00:15 UTC, mori-atsushi approved these changes
動きました

2019-01-30 00:15 UTC, Mori-Atsushi commented on README.md
> +```
これの書き方知りたい

2019-01-30 00:34 UTC, euglena1215 commented on README.md
> +```
愚直に手打ちしましたが(食い気味)

2019-01-30 03:16 UTC, tanishi requested changes
全体的に良さそう。
1点だけすぐ終わる修正:pray:

2019-01-30 03:16 UTC, tanishi commented on package.json
> +    "start": "NODE_ENV=development ./node_modules/.bin/nodemon --exec ./node_modules/.bin/babel-node src/index.ts --extensions '.ts'",
`npm scripts`
の中では`node_modules/bin`にパス通されるから
`nodemon --exec ./node_modules/.bin/babel-node src/index.ts --extensions '.ts'"`
で良さそう

2019-01-30 03:16 UTC, tanishi commented on package.json
> +    "build": "./node_modules/.bin/babel ./src --out-dir lib --extensions '.ts'",
ここも

2019-01-30 03:16 UTC, tanishi commented on package.json
> +    "tsc": "./node_modules/.bin/tsc -p . --noEmit"
ここも

2019-01-30 05:19 UTC, euglena1215 commented on package.json
> +    "start": "NODE_ENV=development ./node_modules/.bin/nodemon --exec ./node_modules/.bin/babel-node src/index.ts --extensions '.ts'",
知らんかった :eyes:

2019-01-30 13:55 UTC, remew reviewed
全体的に問題なさそうだけどいくつか細かいコメントだけしてます

2019-01-30 13:55 UTC, remew commented on README.md
> +```
PlantUML記法使ったほうが良さそう

2019-01-30 13:55 UTC, remew commented on package.json
> +  "author": "Shintani Teppei <teppest1215@gmail.com>",
細かいところだけどauthorこれでいいの？ｗ

2019-01-30 18:29 UTC, euglena1215 commented on package.json
> +  "author": "Shintani Teppei <teppest1215@gmail.com>",
いいのというのは個人情報的な話？cyder名義じゃなくていいのという話？

個人情報の話ならまあいいでしょって思ってる、cyder名義は分からないので @Mori-Atsushi に意見を仰ぎたい

2019-01-30 19:08 UTC, euglena1215 commented on README.md
> +```
確かにPlantUML使った方が綺麗に画像として書き出せそう、ただこの状態から修正すべきですかね？
PlantUML原理主義派でPlantUMLじゃないとDXが極端に下がるという話なら一刻も早く修正します、

2019-01-31 03:18 UTC, Mori-Atsushi commented on package.json
> +  "author": "Shintani Teppei <teppest1215@gmail.com>",
なんでもいいんじゃないかな（ハナホジ）
Cyder <contact@cydewr.tech> でもいいと思う

2019-01-31 08:58 UTC, tanishi approved these changes

2019-01-31 13:09 UTC, remew commented on README.md
> +```
今後機会があったらで大丈夫です！

2019-01-31 13:09 UTC, remew commented on package.json
> +  "author": "Shintani Teppei <teppest1215@gmail.com>",
意図としては後者だった

2019-01-31 13:34 UTC, euglena1215 commented on package.json
> +  "author": "Shintani Teppei <teppest1215@gmail.com>",
かしこまった

2019-01-31 13:43 UTC, merged